version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app  
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "5173:5173"